### ISSUE TITLE
v2 - Missing required parameters for [Route: ]

### ISSUE THREAD

**Issue by jessarcher** [livewire/livewire#1486]
### Description

When mapping a route to a Livewire component using route parameters, the initial page load is fine, but any data binding or actions trigger the following error:

> Illuminate\Routing\Exceptions\UrlGenerationException
> Missing required parameters for [Route: ] [URI: posts/{id}]. 

The problem seems to occur both with standard route parameters (e.g. id, slug, whatever) as well as route model binding.

For reproduction steps I'm just keeping it simple with an `id` parameter and no database request or anything.

### Steps to reproduce

```sh
php artisan livewire:make ShowPost
```

Add the following `routes/web.php`:

```php
use App\Http\Livewire\ShowPost::class;

Route::get('/posts/{id}', ShowPost::class);
```

Create a simple component with some data binding or an action. E.g.

```php
// app/Http/Livewire/ShowPost.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class ShowPost extends Component
{
    public $post;

    public $someField = '';

    public function mount($id)
    {
        $this->post = "pretending to get a post from the $id";
    }

    public function render()
    {
        return view('livewire.show-post');
    }
}
```

```blade
// resources/views/livewire/show-post.blade.php
<div>
    <h1>Show Post</h1>
    <input type="text" wire:model="someField">
</div>
```

Now visit `/posts/123` and see the view rendered successfully, but as soon as you type in the input field, get the aforementioned error.

As mentioned, I've tried with different parameter name (e.g. slug) and I've tried it with route model binding as well. All of them work for the initial page load, but get the same error as soon as it makes a request to the server (data binding or an action)

**Context**
- Livewire version: v2.0.0
- Laravel version: v7.27.0 (also happens with 8.x beta)
- Browser: Firefox

**Comment by calebporzio** [comment]
Ok, great catch, thanks for submitting @jessarcher!

I believe the problem should be all solved in v2.0.3

Re-open if it's not

**Comment by jasminetracey** [comment]
@calebporzio This error still exists i'm using version 2.2.3

**Comment by ssang** [comment]
Sorry if I shouldn't be re-opening this so far after it was closed but I'm currently on v2.4.0 and having the same issue.

My code is similar to the above for a Product model with quantity property wired to an input but any time I change the quantity, I get the same message:

`Missing required parameter for [Route: product] [URI: product/{product}] [Missing parameter: product].`
