### ISSUE TITLE
Cannot read property 'fingerprint' of null

### ISSUE THREAD

**Issue by jasontxf** [livewire/livewire#1686]
### Description
The pagination only works the first time. After that it stops working. When I go into the console. This is the error I see.

<img width="695" alt="Screenshot 2020-09-24 at 6 45 21 PM" src="https://user-images.githubusercontent.com/1124731/94136121-0a077880-fe97-11ea-9651-1742734a92bd.png">

### Exact steps to reproduce

Followed https://laravel-livewire.com/docs/2.x/pagination to implement pagination

Include WithPagination
```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use Livewire\WithPagination;

class Files extends Component
{
	use WithPagination;
	
	public function render()
	{
		$files = authUser()->watchedFiles()->paginate(5);
		
		return view('livewire.files', [
			'files' => $files,
		])->extends('layouts.app');
	}
}
```
 
Using the default pagination
```html
{{$files->links()}}
```

When I monitored the network connection
I noticed that livewire included the fingerprint in the request. 

<img width="697" alt="Screenshot 2020-09-24 at 6 55 21 PM" src="https://user-images.githubusercontent.com/1124731/94136565-b21d4180-fe97-11ea-923a-fdb902e1f52b.png">

Here's the response
<img width="964" alt="Screenshot 2020-09-24 at 6 55 09 PM" src="https://user-images.githubusercontent.com/1124731/94137094-7df65080-fe98-11ea-8d2a-360037c7607f.png">

Please let me know if you require any other info. Sorry, this is my first time posting an issue.

**Context**
- Livewire version: 2.2.6
- Laravel version: 7.28.3
- Browser: Chrome 85.0.4183.121

**Comment by amaelftah** [comment]
i faced the same issue too . but my case was pagination + searching

**Comment by jasontxf** [comment]
After troubleshooting for 9 hours,

I've finally found out what's the issue!

Firstly, the pagination display results in a table. Each row contains a nested component for the action column.
The issue happened because the nested component does not include a key identifier. 

Once I've included it in, the pagination works!

```html
// Before
<td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
    <livewire:files-table-actions :watched-file="$watchedFile" />
</td>

// After
<td class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
    <livewire:files-table-actions :watched-file="$watchedFile" :key="$watchedFile->id"/>
</td>
```

Thank you for this wonderful framework!

**Comment by amaelftah** [comment]
@jasontxf i have the same issue while including the **:key**  for the nested component . but am doing search also

**Comment by jasontxf** [comment]
@amaelftah Do you have a code snippet on how are you doing the search?

**Comment by amaelftah** [comment]
yes it;s just a basic search nothing fancy .and this case happens only when i copy a name and  paste it inside the search input while on the same page that shows the item .

for example if i am on page 3 and the rendered item is "Ahmed Brand" . then when i paste "Ahmed Brand" inside the search input it shows the same error

```php
class SelectBrandToShoutout extends Component
{
    use WithPagination;

    public string $channel;

    public string $search = '';

    protected $queryString = [
        'search' => ['except' => ''],
        'page' => ['except' => 1],
    ];

    public function mount()
    {
        $this->fill(request()->only('search', 'page'));
    }

    public function render(GetMatchesQueryLivewireCriteria $criteria, GetMatchesQueryLivewire $query)
    {
        if ($this->search) {
            $this->resetPage();
        }

        $criteria->setType(GetMatchesQueryLivewireCriteria::HOSTING)
            ->setForTeamId(my_team()->id)
            ->setSearch($this->search)
            ->setPaginatePerPage(1);

        return view('livewire.shoutout.select-brand-to-shoutout', [
            'teams' => $query->setCriteria($criteria)->execute(),
        ]);
    }
}


```


```html
inside livewire.shoutout.select-brand-to-shoutout

<input wire:model.debounce.200ms="search" >

 @foreach ($teams as $team)
        <livewire:matching.card :channel="$channel" :key="$team->id" :team="$team"/>
  @endforeach


```

**Comment by jasontxf** [comment]
@amaelftah I might have the solution to your problem. I think $this->resetPage() should not be in render(). Instead, it's probably better to put it in updated()

```php
public function updated($name)
{
    if ($name === 'search') {
        $this->resetPage();
    }
}
```

Give it a try :)

**Comment by amaelftah** [comment]
@jasontxf thanks for the suggestion i tried it bu it didn't work and produced the same error :cry:

**Comment by jasontxf** [comment]
@amaelftah After trying out multiple results in the wire:model, I manage to hit your error too. This is so bizarre...

**Comment by amaelftah** [comment]
@jasontxf  i feel it's something with pagination inside livewire . so it needs some deep digging into the core

**Comment by jasontxf** [comment]
@amaelftah  I think I've figured it out. 

I noticed when the result is returning properly, this happened

<img width="1001" alt="Screenshot 2020-09-25 at 2 03 36 AM" src="https://user-images.githubusercontent.com/1124731/94182574-ca12b680-fed3-11ea-9722-8f1003b79230.png">

and when the error appear, this is what I see
<img width="1005" alt="Screenshot 2020-09-25 at 2 03 46 AM" src="https://user-images.githubusercontent.com/1124731/94182655-e3b3fe00-fed3-11ea-97eb-918e21fbe8a2.png">

So I'm guessing the nested component for some reason is being generated twice.
It might be because it has the same id for key.

So I tried this hacky method to always generate a different key 

```html
@php
    $randomKey = time().$watchedFile->id;
@endphp
<livewire:files-table-actions :watched-file="$watchedFile" :key="$randomKey"/>
```

and I'm no longer facing the issue.

I'm not sure why is the previous nested component not clearing itself. 

Perhaps @calebporzio could point us to what are we doing wrongly :)

**Comment by amaelftah** [comment]
@jasontxf your solution worked perfectly . you are awsome man thanks a lot :clap:

**Comment by jasontxf** [comment]
@amaelftah Glad to hear that! Hopefully @calebporzio could show us the proper way of doing this.

**Comment by coxlr** [comment]
I just hit the same issue when deleting items from a table where each row is a nested livewire component. Adding a timestamp to the key as @jasontxf suggested fixed my issue. 

```<livewire:accounts-item :account="$account" :key="time().$account->id"/>```

It would be good to know if there a proper way to handle this.

**Comment by jasontxf** [comment]
I didn't know I could run PHP expression within :key! Thanks for helping to shorten my fix :)

**Comment by dniccum** [comment]
I am currently getting this as well with a for loop within a component. I have tried adding the key attribute to my loop with no luck.

```
 wire:key="{{ $loop->index }}"
```

**Comment by coxlr** [comment]
@dniccum try using just ''':key=''' instead of '''wire:key='''

**Comment by jasontxf** [comment]
@dniccum Does the workaround works for you?

```html
:key="time().$loop->index"
```

**Comment by dniccum** [comment]
Just updated my code and I am still getting the same Javascript error.

```html
@foreach($plans as $plan)
    <div wire:click="selectPlan('{{ $plan->plan }}')" :key="{{ $loop->index }}">
        <!-- content here -->
    </div>
@endforeach
```

The parent component is this:

```html
<x-jet-dialog-modal wire:model="showCreate">
        <x-slot name="title">
            <div class="text-gray-400 font-light text-sm">Select the plan that you would like.</div>
        </x-slot>
        <x-slot name="content">
            <div>
                <livewire:plan-select />
            </div>
        </x-slot>
        <x-slot name="footer">

        </x-slot>
</x-jet-dialog-modal>
```

**Comment by jasontxf** [comment]
@dniccum have you tried this?

```html
@foreach($plans as $plan)
    <div wire:click="selectPlan('{{ $plan->plan }}')" :key="{{ time().$loop->index }}">
        <!-- content here -->
    </div>
@endforeach
```

**Comment by dniccum** [comment]
@jasontxf Unfortunately the same result.

**Comment by dniccum** [comment]
Found the issue. This error occurs if you are loading Vue into the page (part of the default Laravel installation) **IN ADDITION** to the Livewire scripts tag. Remove Vue from the page and everything should work. This also solves an issue where the event emitters and listeners were colliding.

**Comment by jasontxf** [comment]
Unfortunately, that's not my case as I removed vue upon installation.

**Comment by calebporzio** [comment]
Closing this as the original issue has been resolved. Please re-submit a separate issue and reference it here for anything else. Thanks!

**Comment by jasontxf** [comment]
> @amaelftah I think I've figured it out.
> 
> I noticed when the result is returning properly, this happened
> 
> <img alt="Screenshot 2020-09-25 at 2 03 36 AM" width="1001" src="https://user-images.githubusercontent.com/1124731/94182574-ca12b680-fed3-11ea-9722-8f1003b79230.png">
> 
> and when the error appear, this is what I see
> <img alt="Screenshot 2020-09-25 at 2 03 46 AM" width="1005" src="https://user-images.githubusercontent.com/1124731/94182655-e3b3fe00-fed3-11ea-97eb-918e21fbe8a2.png">
> 
> So I'm guessing the nested component for some reason is being generated twice.
> It might be because it has the same id for key.
> 
> So I tried this hacky method to always generate a different key
> 
> ```
> @php
>     $randomKey = time().$watchedFile->id;
> @endphp
> <livewire:files-table-actions :watched-file="$watchedFile" :key="$randomKey"/>
> ```
> 
> and I'm no longer facing the issue.
> 
> I'm not sure why is the previous nested component not clearing itself.
> 
> Perhaps @calebporzio could point us to what are we doing wrongly :)

Hello @calebporzio I'm sorry to reopen this, but the original issue wasn't resolved. 
Is the intended behavior to always generate a different key (by appending time()) when using nested component?

Thank you for your time!

**Comment by MAbughrara** [comment]
> I just hit the same issue when deleting items from a table where each row is a nested livewire component. Adding a timestamp to the key as @jasontxf suggested fixed my issue.
> 
> ```js
> <livewire:accounts-item :account="$account" :key="time().$account->id"/>
> ```
> 
> It would be good to know if there a proper way to handle this.

that solved the problem, thank man
I tried key('item-'.$item->id) put didn't work

**Comment by quanengineering** [comment]
> I just hit the same issue when deleting items from a table where each row is a nested livewire component. Adding a timestamp to the key as @jasontxf suggested fixed my issue.
> 
> ```js
> <livewire:accounts-item :account="$account" :key="time().$account->id"/>
> ```
> 
> It would be good to know if there a proper way to handle this.

This is the solution. It works!

**Comment by quanengineering** [comment]
> @amaelftah I think I've figured it out.
> 
> I noticed when the result is returning properly, this happened
> 
> <img alt="Screenshot 2020-09-25 at 2 03 36 AM" width="1001" src="https://user-images.githubusercontent.com/1124731/94182574-ca12b680-fed3-11ea-9722-8f1003b79230.png">
> 
> and when the error appear, this is what I see
> <img alt="Screenshot 2020-09-25 at 2 03 46 AM" width="1005" src="https://user-images.githubusercontent.com/1124731/94182655-e3b3fe00-fed3-11ea-97eb-918e21fbe8a2.png">
> 
> So I'm guessing the nested component for some reason is being generated twice.
> It might be because it has the same id for key.
> 
> So I tried this hacky method to always generate a different key
> 
> ```
> @php
>     $randomKey = time().$watchedFile->id;
> @endphp
> <livewire:files-table-actions :watched-file="$watchedFile" :key="$randomKey"/>
> ```
> 
> and I'm no longer facing the issue.
> 
> I'm not sure why is the previous nested component not clearing itself.
> 
> Perhaps @calebporzio could point us to what are we doing wrongly :)

Thanks man :dancing_men:

**Comment by darviscommerce** [comment]
I had the same problem also when ik randomized the key.
By adding a debounce of 200ms the problem was solved

`<input wire:model.debounce.200ms="search" type="text" placeholder="Search..." >`

**Comment by adityar15** [comment]
> @amaelftah I think I've figured it out.
> 
> I noticed when the result is returning properly, this happened
> 
> <img alt="Screenshot 2020-09-25 at 2 03 36 AM" width="1001" src="https://user-images.githubusercontent.com/1124731/94182574-ca12b680-fed3-11ea-9722-8f1003b79230.png">
> 
> and when the error appear, this is what I see
> <img alt="Screenshot 2020-09-25 at 2 03 46 AM" width="1005" src="https://user-images.githubusercontent.com/1124731/94182655-e3b3fe00-fed3-11ea-97eb-918e21fbe8a2.png">
> 
> So I'm guessing the nested component for some reason is being generated twice.
> It might be because it has the same id for key.
> 
> So I tried this hacky method to always generate a different key
> 
> ```
> @php
>     $randomKey = time().$watchedFile->id;
> @endphp
> <livewire:files-table-actions :watched-file="$watchedFile" :key="$randomKey"/>
> ```
> 
> and I'm no longer facing the issue.
> 
> I'm not sure why is the previous nested component not clearing itself.
> 
> Perhaps @calebporzio could point us to what are we doing wrongly :)

Your answer saved my day. Thanks a lot :)

**Comment by lilouch** [comment]
I have the same issue with no table search. Just a basic component looping for Ideas.

**IdeasIndex.php**
```
    use WithPagination;

    public function render()
    {
        $ideas = Idea::with('user', 'category', 'status')
            ->addSelect([
                'voted_by_user' => Vote::select('id')
                    ->where('user_id', auth()->id())
                    ->whereColumn('idea_id', 'ideas.id')
            ])
            ->withCount('votes')
            ->orderBy('id', 'desc')
            ->simplePaginate(Idea::PAGINATION_COUNT);

        return view('livewire.ideas-index', compact('ideas'));
    }
```

**ideas-index.blade.php**

```
<div>
    <div class="ideas-container space-y-6 my-6">
        @foreach($ideas as $idea)
       //Other livewire component
        @endforeach
    </div><!-- end ideas container-->

    <div class="my-8">
        {{ $ideas->links() }}
    </div>
</div>
```

**The error**

```
Uncaught (in promise) TypeError: Cannot read property 'fingerprint' of null
    at new Component (index.js:32)
    at onNodeAdded (index.js:476)
    at callHook (morphdom.js:35)
    at handleNodeAdded (morphdom.js:140)
    at morphdom.js:407
    at morphEl (morphdom.js:219)
    at morphdom.js:332
    at morphEl (morphdom.js:219)
    at morphdom.js:463
    at Component.value (index.js:366)
```

Any help ?

**Comment by adityar15** [comment]
I had the same problem. I used the component something like this

```
@foreach($users as $user)
<livewire:user :key="now()->timestamp.$user->id" />
@endforeach
```

I am passing event from child to the parent component and after the event is triggered, I got the error cannot read property fingerprint of null

I have to change the syntax of wire key

```
@foreach($users as $user)
<livewire:user :wire:key="now()->timestamp.$user->id" />
@endforeach
```

It worked for a while and later after few days, don't know what happened it only worked on live server but not on dev server.

So I have to change it back to 


```
@foreach($users as $user)
<livewire:user :key="now()->timestamp.$user->id" />
@endforeach
```
This time it worked again.

I am not sure why it is like this.

**Comment by rello86** [comment]
I had a very similar issue, but i was not using wire:model.

I was facing the "fingerprint" issue when try to sort a paginated eloquent collection.

The solutions was to adding 
`:key="now()->timestamp.$user->id"`
adding also
`wire:ignore`
in the root tag of the blade template with loop

**Comment by howdu** [comment]
> The solutions was to adding `:key="now()->timestamp.$user->id"` adding also `wire:ignore` in the root tag of the blade template with loop

You got me on the right track but I needed to add `wire:ignore.self`to the root tag. 
> The "self" modifier restricts updates to the element itself, but allows modifications to its children.
