### ISSUE TITLE
Unable to find and render any components on Windows

### ISSUE THREAD

**Issue by adrianschubek** [livewire/livewire#288]
**Describe the bug**
Livewire doesnt find any components on Windows.

**To Reproduce**
1. Run `php artisan make:livewire counter` (follow quickstart docs)
2. Run `php artisan livewire:discover`
2. Trying to display it `@livewire('counter')` will result in:

```
Facade\Ignition\Exceptions\ViewException
Unable to find component: [counter] 
```

**Expected behavior**
A rendered counter component.

**Desktop (please complete the following information):**
 - Windows 10
 - PHP 7.2

**Additional context**
Related PR: https://github.com/livewire/livewire/pull/287

**Comment by WSBrendonBallantyne** [comment]
Hi, I encountered the same when following the quickstart. The livewire-components file remains empty after making the component. 
In my case I manually edited it just to be able to continue the quickstart:
<?php return array('counter' => 'App\\Http\\Livewire\\Counter',);

I'm on:
Laravel 5.8
Windows 8
PHP 7.2

**Comment by calebporzio** [comment]
Should be fixed in the latest release v0.3.8

**Comment by titonova** [comment]
@calebporzio um, the problem is not fixed .... Im using the latest version, but Im having the exact same problem.

**Comment by nkamuo** [comment]
> @calebporzio um, the problem is not fixed .... Im using the latest version, but Im having the exact same problem.

I still have this issue on laravel 9.37 with php8.1 on windows10
