### ISSUE TITLE
The directory must be present and writable. 

### ISSUE THREAD

**Issue by shirazsoft** [livewire/livewire#597]
Hello,
I upgrade 0.7.2 to 0.7.3 and I get:
The directory must be present and writable. (View:resources\views\admin\user\index.blade.php)

My index.blade.php is:
````
@extends('admin.layouts.app')

@section('content')

    <div class="app-title">
        <div>
            <h1><i class="mdi mdi-view-list"></i> همه کاربرها</h1>
            <p>شما در این صفحه همه کاربرها را مشاهده می کنید</p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">داشبرد</a></li>
            <li class="breadcrumb-item active"><a href="{{ route('admin.user') }}">همه کاربرها</a></li>
        </ul>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="tile">
                <div class="tile-title-w-btn">
                    <h3 class="title">همه کاربرها</h3>
                    <p><a class="btn btn-primary icon-btn" href="{{ route('admin.user.create') }}"><i class="mdi mdi-plus"></i>افزودن کاربر	</a></p>
                </div>
                @livewire('admin.user.index')
            </div>
        </div>
    </div>
@endsection

````

My LiveWire file is:
````
<div>
    <input class="form-control mb-1" wire:model="search" type="text" placeholder="نام،عنوان،شماره...">
    <div class="table-responsive">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>#</th>
            <th>شماره</th>
            <th>اقدام ها</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td>{{ $user->mobile }}</td>
                <td>
                    <a href="{{ route('admin.user.edit',[$user->id]) }}" class="btn btn-primary btn-sm"><i class="mdi mdi-file-edit"></i> ویرایش</a>
                    <form method="post" class="d-inline"
                          action="{{ route('admin.user.delete',[$user->id]) }}"
                          style="display:inline;">
                        @csrf
                        @method('delete')
                        <button onclick="return confirm('آیا از عملیات حذف اطمینان دارید؟')"
                                class="btn btn-danger btn-sm"><i
                                class="mdi mdi-trash-can"></i> حذف</button>
                    </form>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
    </div>
    {{ $users->links() }}
</div>

````

**Comment by csoutham** [comment]
I've had this too, but only if I've published the config file via `php artisan vendor:publish`.
Out of the box without doing that, then everything is fine.

**Comment by AEK-BKF** [comment]
I confirm this with last version 0.7.3

**Comment by AEK-BKF** [comment]
@csoutham I did what you said and the error is still appearing !

**Comment by sineld** [comment]
Changing
`'manifest_path' => null,` to `'manifest_path' => base_path('bootstrap/cache/manifest.json'),` and running commands

```
php artisan vendor:publish --tag=livewire:config
php artisan livewire:discover
```

solved issue for me.

**Comment by AEK-BKF** [comment]
Okay ! I fixed it like this :
I change in config/livewire.php :
`'manifest_path' => base_path('bootstrap/cache/livewire-components.php'),`

Then run :
`php artisan config:cache`
Thanks

**Comment by sineld** [comment]
@AEK-BKF yes "livewire-components.php" is better :)

**Comment by osbre** [comment]
Speaking about deployment,

using only:
```bash
php artisan livewire:discover
```
works fine for me. (at least it solves error)

**Comment by kevinpurwito** [comment]
> ```shell
> php artisan livewire:discover
> ```

Hi, sorry that I comment on an old issue, but I got this issue on deployment on Envoyer as well, when do we call this? right after `Activate New Release`  or after `php artisan config:cache` ?

**Comment by joshhanley** [comment]
@kevinpurwito I would probably do it as the last thing before you active the new release.

**Comment by kevinpurwito** [comment]
> @kevinpurwito I would probably do it as the last thing before you active the new release.

@joshhanley ok thanks for the info!

**Comment by joshhanley** [comment]
@kevinpurwito no worries! 🙂
