### ISSUE TITLE
Rapid events get "stuck"

### ISSUE THREAD

**Issue by google-mac** [livewire/livewire#60]
When rapid events are done in succession, it seems that something is held stationary until the next event happens. For example, if I have a counter (like in the docs) and I click twice very quickly, the count is incremented by one (not desired result). This is not just a matter of speed though because if I click increment one more time, the number goes up by two!

**To Reproduce**
1. Create the simple counter as outlined in the docs
2. Click the increment in rapid succession (counting the number of clicks)
3. Verify that the number has not increased to the desired number
4. Click the button once more
5. Verify that it went up more than the desired amount

I expect this to not go up twice on the last click. If there is a lag in the rapid clicking, that is fine (for me, at least). But firing the next event(s) as a package deal could produce very bad results. It seems better to be conservative.

 - OS: Mac
 - Browser Chrome
 - Version 75.0.3770.142

**Comment by connecteev** [comment]
I'm not seeing this (also on Mac and Chrome Version 75.0.3770.142 (Official Build) (64-bit))

**Comment by calebporzio** [comment]
I can confirm this is the current behavior. LIvewire currently queues up actions that weren't able to be sent (because of a current ajax request being processed) and fires them at the same time.

![image](https://user-images.githubusercontent.com/3670578/61958231-f3157f80-af8e-11e9-8ca8-f86a71dd7612.png)

I tend to agree that this behavior should be more conservative, but I know I started that way and moved to this for some reason.

Can we think through some of the real-life implications of this behavior?

**Comment by google-mac** [comment]
My reasons for thinking conservatively is that most systems I come across (and that I would build) would have a conservative base. 

For example, a money exchanging app does not start a transfer off at $1000, but at $0 or perhaps $10. Something lower. Let's say that instead of typing the new amount, there is a button to increment the amount. Then, let's say there is another button (in the same component) that is in charge of submitting that value. When we "submit" it actually "unpacks" the built-up events and submits, though I'm not sure what order it is in. Either way, you will either submit the wrong value OR freak the user out, making them think they submitted the wrong value.

To mimic this, add a button to your counter:

```html
<div style="text-align: center;">
    <button wire:click="increment">+</button>
    <div>{{ $count }}</div>
    <button wire:click="decrement">-</button>

    <br>

    <button wire:click="submit">Submit</button>
</div>
```

Then add the click event:

```php
<?php

namespace App\Http\Livewire;

use Livewire\Component;

class Counter extends Component
{
    public $count = 0;

    public function render()
    {
        return view('livewire.counter');
    }

    public function increment(): void
    {
        $this->count++;
    }

    public function decrement(): void
    {
        $this->count--;
    }

    public function submit(): void
    {
        // do something
    }
}
```

Note that when you rapidly click and get the events stuck and then click submit, the previous events are unpacked. So essentially _the perceived state is different than what it will be_.

Another side effect is that this only seems to be triggered by actions/events from the same component. I tried submitting a button in a separate component and it did not finish the increments waiting to happen. It only happened when I fired the submit method from within the counter.

**Comment by lancepioch** [comment]
One solution could be to add a modifier that disables either the element or model binding or event whenever it's currently taking action.

For example: `wire:click.single="saveModel"`: After being clicked, the element is disabled until Livewire returns back to it.

**Comment by intrepidws** [comment]
I had a similar problem, but in a different scenario. I had users that were making a change in a model-binded lazy input field and then clicking on a `wire:click` enabled button without first clicking or tabbing out of that input field. The result was very similar as has been reported here, with the main difference being that subsequent clicks of that `wire:click` enabled button would return a 404. I'm still not entirely sure why the 404 but I was able to fix by using loading states and disabling the button during loading.

**Comment by robsontenorio** [comment]
Maybe livewire should implement some mechanism “to enforce” components respect the queue.

**Comment by calebporzio** [comment]
I think most of these issues have been fixed.

If someone finds this isn't the case, re-open.

Thanks!

**Comment by azraai** [comment]
@calebporzio I'm still having this issue on 1.1.0

`
<thead>
    <tr>
        <th wire:click="sort('date')">Date</th>
        <th wire:click="sort('col1')">Col1</th>
        <th wire:click="sort('col2')">Col2</th>
     </tr>
</thead>
`

Clicking on `<th>` doesn't fire the actionQueue back to server.
