### ISSUE TITLE
Starting a livewire component with a html comment tag breaks something

### ISSUE THREAD

**Issue by joveice** [livewire/livewire#725]
**Describe the bug**
Adding a html comment tag as the first line breaks the component

**To Reproduce**
1. Go to a component
2. add some comment `<!-- Page title -->`
3. view it

**Expected behavior**
The comment would be written to the page

**Screenshots**
```
< wire:initial-data="{"id":"yU0EEEH6GsylSoXqqZjJ","name":"live-user-search","redirectTo":false,"events":[],"eventQueue":[],"dispatchQueue":[],"data":{"search":"","pages":1,"page":1},"children":[],"checksum":"1a5836b3f57c2f48bd96bd70c50c12bbfaaf26324e604b4c6569f1cfef54db38"}" wire:id="yU0EEEH6GsylSoXqqZjJ"!-- Page title --> 
```

**Desktop (please complete the following information):**
 - Browser: Firefox

**Comment by joveice** [comment]
Looks to be because of the " Livewire components MUST have a single root element. ". But if a comment should break it too must be up to the maintainers to decide. Leaving it open for that.
So if you experience this, move the comment inside the div or don't have it at all.

**Comment by calebporzio** [comment]
Yeah, I'm not going to mess with the root element regex right now. Please put your comments inside the root element. Or if you wish to PR a change with thorough testing to allow this, I'd be up for that as well.

Closing this. Thanks!

**Comment by martincarlin87** [comment]
Thank goodness I finally found this, I was going mad. Was a comment that was breaking it for me also.

**Comment by br13an** [comment]
Hi guys sorry to reopen thus, but is it possible to specify this in the documentation? This one really messed me up.

**Comment by joshhanley** [comment]
@br13an we fixed up the regex a while back to allow comments. Can you share what patch version of Livewire you are on and show us what comment you were trying to put at the beginning of your component? Thanks!

**Comment by br13an** [comment]
@joshhanley Sorry for the late reply, I've just tested it again on version 2.10.6 and 12.10.7 still the same problem.
Just add an HTML comment like;
`<!-- Test Comment -->` 
This makes the component disappear as soon as you interact with it (I do have a few of the same components in a loop on the same page though, but also happens when only rendering 1).
I don't really mind if the problem isn't going to be fixed, but if you could add some explicit warning in the docs could save some people a bit of time finding this one out.
