### ISSUE TITLE
When using a custom pagination view, unable to go to the previous page.

### ISSUE THREAD

**Issue by alexjustesen** [livewire/livewire#872]
**Describe the bug**
While using a custom pagination view, using wire:click"previousPage" doesn't trigger an action.

**To Reproduce**
```php
// Livewire/User/History.php

namespace App\Http\Livewire\User;

use Auth;
use Livewire\Component;
use Livewire\WithPagination;

class History extends Component
{
    use WithPagination;

    public function render()
    {
        $actions = Auth::user()->actions()
                            ->orderBy('created_at', 'desc')
                            ->paginate(2);
        
        return view('livewire.user.history', [
            'actions' => $actions,
        ]);
    }
}
```

```php
// livewire/user/history.blade.php

<div class="flex flex-col">
    <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="align-middle inline-block min-w-full shadow overflow-hidden sm:rounded-lg border-b border-gray-200">
            <table class="min-w-full">
                <thead>
                    <tr>
                        <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                            Action
                        </th>
                        <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                            IP address
                        </th>
                        <th class="px-6 py-3 border-b border-gray-200 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
                            Time
                        </th>
                    </tr>
                </thead>

                <tbody>
                    @if($actions)
                        @foreach($actions as $action)
                        <tr class="bg-white hover:bg-gray-50">
                            <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900">
                                {{ $action->log_name }}.{{ $action->description }}
                            </td>
                            <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                                {{ $action->ip_address }}
                            </td>
                            <td class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500">
                                {{ \Carbon\Carbon::parse( $action->created_at )->DiffForHumans() }}
                            </td>
                        </tr>
                        @endforeach
                    @endif
                </tbody>
            </table>

            {{ $actions->links('livewire.table-pagination') }}
        </div>
    </div>
</div>
```

```php
// livewire/table-pagination.blade.php

@if ($paginator->hasPages())
<div class="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6">
    <div class="hidden sm:block">
        <p class="text-sm leading-5 text-gray-700">
            Showing
            <span class="font-medium">{{ $paginator->firstItem() }}</span>
            to
            <span class="font-medium">{{ $paginator->lastItem() }}</span>
            of
            <span class="font-medium">{{ $paginator->total() }}</span>
            results
        </p>
    </div>

    <div class="flex-1 flex justify-between sm:justify-end">
        <span class="relative z-0 inline-flex shadow-sm">
            @if ($paginator->onFirstPage())
                <button type="button" class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm leading-5 font-medium text-gray-300 transition ease-in-out duration-150 cursor-not-allowed" disabled>
                    <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"/>
                    </svg>
                </button>
            @else
                <button type="button" wire:click="previousPage" rel="prev" aria-label="@lang('pagination.previous')" class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm leading-5 font-medium text-gray-500 hover:text-gray-400 focus:outline-none active:bg-gray-100 active:text-gray-500 transition ease-in-out duration-150">
                    <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd"/>
                    </svg>
                </button>
            @endif

            @if ($paginator->hasMorePages())
                <button type="button" wire:click="nextPage" rel="next" aria-label="@lang('pagination.next')" class="-ml-px relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm leading-5 font-medium text-gray-500 hover:text-gray-400 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100 active:text-gray-500 transition ease-in-out duration-150">
                    <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"/>
                    </svg>
                </button>
            @else
                <button type="button" class="-ml-px relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm leading-5 font-medium text-gray-200 transition ease-in-out duration-150 cursor-not-allowed" disabled>
                    <svg class="h-5 w-5" fill="currentColor" viewBox="0 0 20 20">
                        <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"/>
                    </svg>
                </button>
            @endif
        </span>
    </div>
</div>
@endif
```

**Expected behavior**
On clicking the element with an attribute of wire:click="previousPage" Livewire should supply the previous page.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Chrome (latest 81.0.x)
 - Firefox (latest 75.0.x)

**Additional context**
 - Using spatie's laravel actions package for this example.
 - Livewire styles are in the html head and scripts in the body (at the end) using Laravel 7 tag syntax, loaded in the parent view using blade's push and stack.

```php
// .../views/layouts/app.blade.php

<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" dir="ltr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Shortcut icon -->
        <link rel="shortcut icon" href="">

        <!-- Site title and description -->
        <title>{{ is_string(config('app.page.name')) ? config('app.page.name') : config('app.page.name')[0] }} | {{ config('app.shortname') }}</title>
        <meta name="description" content="{{ config('app.description') }}">

        <!-- Stylesheets -->
        <link rel="stylesheet" href="{{ mix('css/fonts.css') }}">
        <link rel="stylesheet" href="{{ mix('css/app.css') }}">
        @stack('styles')

        <!-- CSRF Token -->
        <meta name="csrf-token" content="{{ csrf_token() }}">
    </head>
    <body class="antialiased bg-gray-100">
        @yield('content')

        <!-- Scripts -->
        <script src="{{ mix('js/manifest.js') }}"></script>
        <script src="{{ mix('js/vendor.js') }}"></script>
        <script src="{{ mix('js/app.js') }}"></script>
        @stack('scripts')
    </body>
</html>
```

```php
// .../views/user/history.blade.php

@extends('layouts.app')

@push('styles')
    <livewire:styles>
@endpush

@section('content')
<div class="">
    @include('layouts.partials._header-nav')

    <header class="bg-white shadow-sm">
        <div class="max-w-7xl mx-auto py-4 px-4 sm:px-6 lg:px-8">
            <h1 class="text-lg leading-6 font-semibold text-gray-900">
                History
            </h1>
        </div>
    </header>

    <main>
        <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
            <div class="grid grid-cols-4 col-gap-8 row-gap-4">
                <div class="col-span-4 md:col-span-1">
                    @include('user.partials._account-nav')
                </div>

                <div class="col-span-4 md:col-span-3">
                    <livewire:user.history>
                </div>
            </div>
        </div>
    </main>
</div>
@endsection

@push('scripts')
    <livewire:scripts>
@endpush
```

**Comment by jetwes** [comment]
I have the exact same problem. The previous Button works if you start at a page > 1 directly in the request | otherwise not...

**Comment by pl38** [comment]
I am seeing something very similar:

using a Laravel Paginating Query Builder works correctly as expected, this query builder:

```

public function render()
{
    $users = User::query()
        ->with('roles', 'permissions')
        ->orderBy($this->sort_by, $this->sort_asc ? 'asc' : 'desc')
        ->when(!$this->trashed, function ($query) {
            return $query->whereActive($this->active);
        })
        ->when($this->trashed, static function ($query) {
            return $query->onlyTrashed();
        })
        ->when($this->search, function ($query) {
            return $query->where('last_name', 'like', "%{$this->search}%")->orWhere('email', 'like', "%{$this->search}%")->orWhere('first_name', 'like', "%{$this->search}%");
        })
        ->paginate($this->paged)
    ;

    return view('livewire.users-table', [
        'users' => $users,
    ]);
}

```

but when creating a LengthAwarePaginator like this:

```
public function render()
{
    $this->page_number = request()->page ?? 1;
    $rows_data = $this->paginate($this->rows);
    return view(
        'livewire.logs-table',
        [
            'rows_data' => $rows_data
        ]
    );
}

protected function paginate(array $data): LengthAwarePaginator
{
    $data = collect($data);
    $page = $this->page_number;
    $path = $this->url;

    return new LengthAwarePaginator(
        $data->forPage($page, $this->paged),
        $data->count(),
        $this->paged,
        $page,
        compact('path')
    );
}
```

both previous and next work but you have to click them twice? so you end up with page 2 in view and 3 in the url and page 1 showing a 0 in the url.

My custom pagination view is:


```
@if ($paginator->hasPages())
    <ul class="pagination flex list-none p-0 pl-0" role="navigation">
        {{--         Previous Page Link--}}
        @if ($paginator->onFirstPage())
            <li class="page-item disabled px-3 py-2 bg-gray-100 text-gray-400 rounded-l" aria-disabled="true" aria-label="@lang('pagination.previous')">
                <span class="page-link" aria-hidden="true">
                    <span class="block md:hidden">&lsaquo;</span>
                    <span class="hidden md:block">@lang('pagination.previous')</span>
                </span>
            </li>
        @else
            <li class="page-item">
                <button type="button" class="page-link px-3 py-2 bg-gray-200 text-gray-700 rounded-l hover:bg-teal-400" wire:click="previousPage">
                    <span class="block md:hidden">&lsaquo;</span>
                    <span class="hidden md:block">@lang('pagination.previous')</span>
                </button>
            </li>
        @endif

        {{--         Pagination Elements--}}
        @foreach ($elements as $element)
            {{--             "Three Dots" Separator--}}
            @if (is_string($element))
                <li class="page-item disabled px-3 py-2 bg-gray-200 text-gray-600 d-none d-md-block" aria-disabled="true">
                    <span class="page-link">{{ $element }}
                    </span>
                </li>
            @endif

            {{--             Array Of Links--}}
            @if (is_array($element))
                @foreach ($element as $page => $url)
                    @if ($page == $paginator->currentPage())
                        <li class="page-item px-3 py-2 bg-teal-700 text-gray-100" aria-current="page"><span class="page-link">{{ $page }}</span></li>
                    @else
                        <li class="page-item px-3 py-2 bg-gray-200 text-gray-700 hover:bg-teal-400"><button type="button" class="page-link" wire:click="gotoPage({{ $page }})">{{ $page }}</button></li>
                    @endif
                @endforeach
            @endif
        @endforeach§

        {{--         Next Page Link--}}
        @if ($paginator->hasMorePages())
            <li class="page-item">
                <button type="button" class="page-link px-3 py-2 bg-gray-200 text-gray-700 rounded-r hover:bg-teal-400" wire:click="nextPage">
                    <span class="hidden md:block">@lang('pagination.next')</span>
                    <span class="block md:hidden">&rsaquo;</span>
                </button>
            </li>
        @else
            <li class="page-item disabled px-3 py-2 bg-gray-100 text-gray-400 rounded-r" aria-disabled="true" aria-label="@lang('pagination.next')">
                <span class="page-link" aria-hidden="true">
                    <span class="hidden md:block">@lang('pagination.next')</span>
                    <span class="block md:hidden">&rsaquo;</span>
                </span>
            </li>
        @endif
    </ul>
@endif
```


no sure what's happening and thoughts very welcome.

**Comment by dave-alvarez** [comment]
I was able to fix this issue by adding ids to all of the elements in my pagination view.

**Comment by pl38** [comment]
> I was able to fix this issue by adding ids to all of the elements in my pagination view.  

Unfortunately I've tried the same but it didn't work for me.

I think when using a LengthAwarePaginator  in mount() I call a contract class which returns an array to be added to the Livewire Component  as `$this->all_rows` . 

```
/**
 * @param LogViewerContract $logViewer
 */
public function mount(LogViewerContract $logViewer): void
{
    $this->logViewer = $logViewer;
    $this->stats = $this->logViewer->statsTable();
    $this->all_rows = $this->stats->rows();
    $this->headers = $this->stats->header();
    $this->action_target = 'blah';
}

```

On first render `$this->all_rows` is passed to 

```
/**
* Paginate logs.
* @param array|Collection $data
* @param Request $request
* @return LengthAwarePaginator
*/
protected function paginate(array $data, Request $request): LengthAwarePaginator
{
    $data = collect($data)->map(
        *static function*($row_item) {
            *return*(*object*)$row_item;
        }
    );
    $page = $request->get('page', 1);
    $path = $request->url();
    $this->current_page = $page;
    $this->page_number = $page;
    $this->url = $path;
    $pageName = 'page';

    *return new*LengthAwarePaginator(
        $data->forPage($page, $this->paged),
        $data->count(),
        $this->paged,
        $page,
        compact('path', 'pageName')
    );
```

which returns the paginated collection which is sent by the render() to the view

```
/**
 * @return Application|Factory|View
 */
public function render()
{
    $rows_data = $this->paginate($this->all_rows, request());
    return view(
        'livewire.logs-table',
        [
            'rows_data' => $rows_data
        ]
    );
}

```

when a change occurs in Livewire the $rows_data from the previous render() is in the request (part of the DOM) but is not being sent to the paginator.

A second click on the $links page causes mount() to fire again (or maybe another render()) and the $rows_data is requested again and the paginate function is called with the new parameters for that page.

The LengthAwarePaginator returns a collection which has to be turned to an array to be a public var available to Livewire and I suspect the issue is this?

For the minute I'm using Livewire components where I have exclusively an Eloquent Model but using controllers for anything else.

**Comment by drfraker** [comment]
For what it's worth. I had this issue and I also added Id's to all items in the paginator that were repetitive, making it difficult for Livewire to diff and the problem was solved. I used a similar view as @alexjustesen and the i also had to add unique id's to this section:

```
<p class="text-sm leading-5 text-gray-700">
            Showing
            <span class="font-medium">{{ $paginator->firstItem() }}</span>
            to
            <span class="font-medium">{{ $paginator->lastItem() }}</span>
            of
            <span class="font-medium">{{ $paginator->total() }}</span>
            results
</p>
```

**Comment by alexjustesen** [comment]
@drfraker I'm hoping to spend some time on the IDs tonight at least as it relates to my example above, I'll report back with any findings later on.

**Comment by alexjustesen** [comment]
@drfraker any chance you can share your code with the IDs? I tried applying some to that section and it didn't resolve the issue.

**Comment by drfraker** [comment]
https://gist.github.com/drfraker/ff28abf4a8eb5cfc0a85cd2d9da3211d

**Comment by senocak** [comment]
> I was able to fix this issue by adding ids to all of the elements in my pagination view.

That actually worked. :)

**Comment by abishekrsrikaanth** [comment]
> I was able to fix this issue by adding ids to all of the elements in my pagination view.

I have a similar issue (https://github.com/livewire/livewire/discussions/1111) and adding the ids helped me as well.

**Comment by abishekrsrikaanth** [comment]
ok, so I thought `id` on the elements was the issue, but it is not the case. I have another project that now has the `id`'s for the pagination elementsa nd I still seem to have this issue.

**Comment by Hesammousavi** [comment]
@calebporzio 
when do u want to fix it ?
it's not related to page id elements . it's something else.

**Comment by mattharcourt** [comment]
The problem appears to be that the "previous" button is being rendered without a `wire:click` directive when inactive, and then with a `wire:click` directive when active, as follows
```php
    @if ($paginator->onFirstPage())
        <button disabled>Previous</button>
    @else 
        <button wire:click="previous">Previous</button>
    @endif
```
The result is that Livewire updates the attributes on the button, but doesn't add a click handler for the `wire:click` directive. A similar problem can occur for the next page button if the `wire:click` directive is removed. 

This suggests two work-arounds:
1. Add the `wire:click` directive to both the disabled and active versions of the button - the disable attribute will prevent the click event from triggering the `wire:click` action.
2. Add an `id` or `wire:id` such that the two versions have different ids (or add an id to just one or the other version). Then Livewire will see the buttons as different elements and completely replace one for the other, and in the process add the click handler for the `wire:click` directive.

**Comment by jetwes** [comment]
> The problem appears to be that the "previous" button is being rendered without a `wire:click` directive when inactive, and then with a `wire:click` directive when active, as follows
> 
> ```
>     @if ($paginator->onFirstPage())
>         <button disabled>Previous</button>
>     @else 
>         <button wire:click="previous">Previous</button>
>     @endif
> ```
> 
> The result is that Livewire updates the attributes on the button, but doesn't add a click handler for the `wire:click` directive. A similar problem can occur for the next page button if the `wire:click` directive is removed.
> 
> This suggests two work-arounds:
> 
> 1. Add the `wire:click` directive to both the disabled and active versions of the button - the disable attribute will prevent the click event from triggering the `wire:click` action.
> 2. Add an `id` or `wire:id` such that the two versions have different ids (or add an id to just one or the other version). Then Livewire will see the buttons as different elements and completely replace one for the other, and in the process add the click handler for the `wire:click` directive.

Perfect explanation!

**Comment by calebporzio** [comment]
Closing this because it's been open too long - re-submit new issue to re-raise

**Comment by EduCavalheiro** [comment]
> I was able to fix this issue by adding ids to all of the elements in my pagination view.

Sweet!

**Comment by helturkey** [comment]
> I was able to fix this issue by adding ids to all of the elements in my pagination view.

thanks, you saved my day searching about it, I faced it in livewire 3 and suffered searching for a solution, although it works fine in livewire 2.
