### ISSUE TITLE
@this.set does not pass through blade components 

### ISSUE THREAD

**Issue by booni3** [livewire/livewire#911]
This does not work:

```html
<x-modal @open-modal.window="@this.set('var', true)">
   <!-- -->
</x-modal>
```

With error:

```
VM9176:3 Uncaught SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at saferEvalNoReturn (app.js:3024)
    at Component.evaluateCommandExpression (app.js:4381)
    at runListenerHandler (app.js:3649)
    at handler (app.js:3633)
    at app.js:4388
    at eval (eval at saferEvalNoReturn (app.js:3024), <anonymous>:3:21)
    at saferEvalNoReturn (app.js:3024)
    at Component.evaluateCommandExpression (app.js:4381)
    at runListenerHandler (app.js:3649)
```

This is a similar issue to #868 which was fixed in Laravel 7.9.0. The above issue is present with 7.9.2.

**Comment by booni3** [comment]
As a workaround, you can actually just duplicate the listener inside the component. So this does work:

```html
<x-modal @open-modal.window="show">
   <div @open-modal.window="@this.set('var', true)
</x-modal>
```

**Comment by mblarsen** [comment]
Is `@open-modal.window` alpine. In that case does this work?

```blade
<x-modal :x-on:open-modal.window="@this.set('var', true)">
```

Note the `:` in front of `x-on`.

**Comment by booni3** [comment]
In this case, we get a `Call to undefined function set()` exception, but it does seem to make some difference.

Going back to the original syntax without the colon prefix, I get this as the attribute bag. It seems to pass it through without converting it to the livewire component first.

<img width="431" alt="Screenshot 2020-05-09 at 17 31 20" src="https://user-images.githubusercontent.com/20134485/81479443-09898080-921b-11ea-9e25-53749ff3ce2d.png">

<img width="432" alt="Screenshot 2020-05-09 at 17 34 01" src="https://user-images.githubusercontent.com/20134485/81479471-5b320b00-921b-11ea-88db-879feb28bc07.png">

My fix for now, is to wrap the button inside another div/span and apply the alpine directive to that.

```blade
<span @click.prevent="@this.call('login')">
    <x-input.submit class="btn btn-primary w-full">
      Login
    </x-input.submit>
  </span>
```

**Comment by fredericseiler** [comment]
My workaround:

`resources/views/components/button.blade.php`
```blade
@props(['alpine' => null])

<button {{ $alpine }} {{ $attributes }}>
{{ $slot }}
</button>
```

`resources/views/livewire/component.blade.php`
```blade
<x-button x-data="{}">
  <x-slot name="alpine">
    x-on:click="@this.set('loading', true); @this.call('something')"
  </x-slot>
  Press me
</xbutton>
```

**Comment by calebporzio** [comment]
This should be fixed now. I verified that I can reference @this in a nested blade component. Closing, thanks!

**Comment by booni3** [comment]
Sorry @calebporzio, I still cannot see this working. I have updated Alpine and Livewire to latest versions. I am trying to pass `@this` through the Laravel blade component attributes.

To clarify my setup:

```html
<!-- modal.blade.php -->
<div x-data="{}" {{ $attributes }}>
    {{ $slot }}
</div>
```

```html
<x-modal x-on:open-modal.window="@this.call('method')">
    <!-- Modal Content -->
</x-modal>
```

Throws error:

```
VM53068:3 Uncaught SyntaxError: Invalid or unexpected token
    at new Function (<anonymous>)
    at saferEvalNoReturn (app.js:3067)
    at Component.evaluateCommandExpression (app.js:4525)
    at runListenerHandler (app.js:3735)
    at HTMLDivElement.handler (app.js:3712)
    at Proxy.dismiss (app.js:26977)
    at saferEvalNoReturn (app.js:3063)
    at Component.evaluateCommandExpression (app.js:4525)
    at runListenerHandler (app.js:3735)
    at HTMLButtonElement.handler (app.js:3712)
```

at:
```js
(function anonymous(dataContext,$event,$dispatch
) {
with(dataContext) { @this.call('method') }
})
```

**Comment by booni3** [comment]
My workarounds to this currently are:

**Option 1 - if using global JS scopes**
Add the listener inside or outside of the parent tag.
```html
<x-modal>
   <div x-on:modal-dismissed.window="@this.call('resetItems')"></div>
   <!-- modal content -->
</x-modal>
```

**Option 2 - when using component scope**
When you do not want to use the global component, the only way I have found to add this to a blade component is by using the livewire event dispatcher

```html
<x-modal x-on:modal-dismissed="window.livewire.emit('resetItems')">
   <!-- modal content -->
</x-modal>
```
