### ISSUE TITLE
Browsersync causing error.

### ISSUE THREAD

**Issue by mikebronner** [livewire/livewire#996]
### Description
When using browsersync with Livewire, I get the following error:
```
Livewire encountered corrupt data when trying to hydrate the [genealabs-laravel-casts::combobox] component. Ensure that the [name, id, data] of the Livewire component wasn't tampered with between requests.
```

When not using browser sync everything works as expected. Is there a special work-around or setting for browsersync?

Thanks!

**Comment by josespinal** [comment]
Are you using Turbolinks?

**Comment by mikebronner** [comment]
No. I forgot off the top of my head what the example is. I will try to put one together tomorrow.

**Comment by josespinal** [comment]
Yes, paste in here how you are initializing BrowserSync w/ options too.

**Comment by nuernbergerA** [comment]
Hey @mikebronner,

if possible share actual code or at least detailed steps to reproduce - so it's easier for us to help you.

**Comment by mikebronner** [comment]
Hmmm, I was trying to replicate the issue, but it looks like it might have been resolved in the 1.2.0 update. I will report back if I can replicate it. :)

**Comment by AdamEsterle** [comment]
I believe this is still broken when running browsersync and using :3000 for the URL (without the :3000) everything works fine

**Comment by mikebronner** [comment]
@AdamEsterle thanks for updating on this. I will re-open. I am using browser sync currently, and have not encountered issues.

**Comment by AdamEsterle** [comment]
Pardon my premature opening. I updated Livewire and everything works fine, I was on 2.something, but we're all good! Can be closed

**Comment by mikebronner** [comment]
Gotcha :) Thanks for checking back in.

**Comment by squishythejellyfish** [comment]
👋 Oh Hi! I'm Squishy, the friendly jellyfish that manages Livewire issues.

I see this issue has been closed.

Here in the Livewire repo, we have an "issues can be closed guilt-free and without explanation" policy.

If for ANY reason you think this issue hasn't been resolved, PLEASE feel empowered to re-open it.

Re-opening actually helps us track which issues are a priority.

Reply "REOPEN" to this comment and we'll happily re-open it for you!

(More info on this philosophy here: https://twitter.com/calebporzio/status/1321864801295978497)
